version: '3'
services:
  postgres:
    image: momlookhowican/postgres
#    volumes:
#      - '/home/deploy/water_ban:/docker-entrypoint-initdb.d'
#      - '/var/lib/postgresql/data/pgdata:/var/lib/postgresql/data/pgdata'
  elasticsearch:
    image: momlookhowican/elasticsearch
#    volumes:
#      - '/home/deploy/water_ban/data:/usr/share/elasticsearch/data'
    # environment:
    #  ES_JAVA_OPTS: -Xms512m -Xmx512m
  web:
    image: momlookhowican/water_ban
#    volumes:
#      - '/home/deploy/water_ban:/usr/src/app/dump'
    environment:
      - RACK_ENV=production
      - RAILS_ENV=production
      - SECRET_KEY_BASE=verysecret
      - DB_HOST=postgres
      - DB_NAME=water_ban_production
      - DB_USER=postgres
      - DB_PASSWORD=blahblah
      - ELASTIC_HOST=elasticsearch
      - ELASTIC_PORT=9200
    ports:
      - "4000:4000"
    command: sh bin/web.sh
    depends_on:
      - postgres
      - elasticsearch

#version: '3'
#services:
#  postgres:
#    image: momlookhowican/postgres
#    volumes:
#      - '/var/lib/postgresql/data/pgdata:/var/lib/postgresql/data/pgdata'
#  elasticsearch:
#    image: momlookhowican/elasticsearch
#  web:
#    image: momlookhowican/water_ban
#    volumes:
#        - '/home/deploy/water_ban:/usr/src/app/dump'
#    environment:
#      - RACK_ENV=production
#      - RAILS_ENV=production
#      - SECRET_KEY_BASE=verysecret
#      - DB_HOST=postgres
#      - DB_NAME=water_ban_production
#      - DB_USER=postgres
#      - DB_PASSWORD=blahblah
#      - ELASTIC_HOST=elasticsearch
#      - ELASTIC_PORT=9200
#    ports:
#      - "8080:4000"
#    command: sh bin/web.sh
#    depends_on:
#      - postgres
#      - elasticsearch

#docker-compose run web.sh bin/rails db:environment:set RAILS_ENV=development


#docker-compose run web.sh rake db:setup RAILS_ENV=development

#docker-compose run web.sh rake db:create
#docker-compose run web.sh rake db:migrate