development: &default
  adapter: postgresql
  encoding: unicode
  database: myapp_development
  pool: 5
#  username: postgres
#  password: password
#  host: db

test:
  <<: *default
  database: myapp_test

production:
  <<: *default
  host:     <%= ENV['DB_HOST'] %>
  adapter:  <%= ENV['DB_ADAPTER'] || 'postgresql' %>
  database: <%= ENV['DB_NAME'] %>
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>